openapi: 3.0.2
info:
  title: "Consumer service"
  description: "OpenApi definition for the consumer service"
  version: 1.0.0
  contact:
    name: Feature teams
    email: oliver.crook@rabobank.nl
servers:
  - url: https://consumer-service-test.apps.pcf-t02-we.rabobank.nl
    description: "Test url"

tags:
  - name: consumer
    description: "Consumer controller"
paths:
  /consumer/products/{productCategory}:
    get:
      tags:
        - consumer
      operationId: getProductList
      parameters:
        - name: productCategory
          in: path
          required: true
          schema:
            type: string
            pattern: '^\w{1,35}$'
      responses:
        200:
          description: Successfully retrieved search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPrices'
        400:
          description: "Bad request"
        500:
          description: "Server error"

components:
  schemas:
    ProductPrices:
      type: object
      properties:
        products:
          type: array
          description: "A list of products and their prices"
          items:
            $ref: '#/components/schemas/ProductPrice'
        promotionDetails:
          type: string
          description: "details of any promotion"
    ProductPrice:
      type: object
      description: 'Details of the product'
      properties:
        code:
          type: string
          description: 'The product code'
        name:
          type: string
          description: 'The product name'
        description:
          type: string
          description: 'The product desceription'
        price:
          type: string
          description: 'The product price'