server:
  port: 8082

logging:
  level:
    root: info
  pattern:
    level: '%-5p [%X{test-case}]ever [%t] %C{2} - %m%n'

spring:
  main:
    web-application-type: none

wiremock:
  server:
    stubs: classpath*:/**/mappings/**/*.json
    files: classpath:/stubs



